
services:
  dev:
    image: dev:latest
    container_name: dev
    build:
      dockerfile: dev.dockerfile
      context: .
    volumes:
      - server:/workspace/
      - ${HOME}/.aws:/root/.aws:ro
    privileged: true
    depends_on: 
      - django-server

  django-server:
    container_name: server
    build:
      dockerfile: .devcontainer/django-server.dockerfile
      context: ./..
    volumes:
      - server:/server/
      - ${HOME}/.aws:/root/.aws:ro
    ports:
      - "8000:8000"
    restart: always

volumes:
  server: