
services:
  dev:
    container_name: dev
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    volumes:
      - server:/workspace/
      - /var/run/docker.sock:/var/run/docker.sock 
    privileged: true

  django-server:
    container_name: server
    build:
      dockerfile: django-server.dockerfile
    volumes:
      - server:/server/

volumes:
  server: