
services:
  dev:
    container_name: dev
    build:
      dockerfile: dev.dockerfile
    volumes:
      - server:/workspace/
      - /var/run/docker.sock:/var/run/docker.sock 
    privileged: true
    depends_on: 
      - django-server

  django-server:
    container_name: server
    build:
      dockerfile: .devcontainer/django-server.dockerfile
      context: ./..
    volumes:
      - server:/server/
    ports:
      - "8000:8000"
    restart: always

volumes:
  server: