name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running auto deploy"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx with local driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker 

      - name: Build Docker image with a specific Dockerfile
        run: docker build -t server:latest -f ./.devcontainer/django-server.dockerfile .

      - name: Run container to test
        run: docker run --rm server:latest