name: Deploy
run-name: ${{ github.actor }} deploy
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running auto deploy"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Load AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials
          echo "${{ env.AWS_CONFIG }}" > ~/.aws/config

      - name: Set up Docker Buildx with local driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker 

      - name: Build containers
        uses: devcontainers/ci@v0.3
      
      - name: Basic health check
        run: docker compose -f .devcontainer/compose.yml up --detach --wait-timeout 10
