name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running auto deploy"

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Load AWS Credentials
        run: |
          mkdir -p ~/.aws
          echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials
          echo "${{ env.AWS_CONFIG }}" > ~/.aws/config

      - name: Set up Docker Buildx with local driver
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker 

      - name: Build Docker image with a specific Dockerfile
        run: docker compose up -d

      - name: Wait for the server to be ready
        run: |
          echo "Waiting for server to start..."
          until curl -s http://localhost:8000 > /dev/null; do
            echo "Waiting for server..."
            sleep 5
          done
          echo "Server is up!"

      - name: Run tests (or further actions)
        run: curl http://localhost:8000  